### ISSUE TITLE
Social media promotion checklist

### ISSUE THREAD

**Issue by jevonmao** [jevonmao/PermissionsSwiftUI#16]
- [x] Post on my personal Instagram
- [x] Post on my personal Twitter
- [x] Reddit preview video - Swift
- [x] Reddit preview video - SwiftUI
- [x] Reddit preview video - iOS Developer
- [x] Reddit promo post - Swift
- [x] Reddit promo post - SwiftUI
- [x] Reddit promo post - iOS Developer
- [x] Project Hunt
- [x] Beta Page
- [ ] Email the Redditor who talked about a SwiftUI lecture session
- [ ] Hackathons
- [ ] HackerNews (Sunday)
